# Generated by Django 5.2 on 2025-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_movie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(default="def", max_length=255),
            preserve_default=False,
        ),
    ]
